name: Validate library data

on: 
    pull_request:
    push:

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the repository
                uses: actions/checkout@v3
            -   name: Validate YAML based on the schema
                uses: GrantBirki/json-yaml-validate@v2.3.0
                with:
                    json_schema: schema/bibliodata.json
                    base_dir: data
    